name: Inspect Code
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  inspect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: JetBrains ReSharper Inspect Code
        uses: JetBrains/ReSharper-InspectCode@v0.11
        with:
          # Path to the file to use custom settings from (default: Use R#'s solution shared settings if exists)
          settings: # optional
          # Write inspections report to specified file
          output: # optional, default is results.sarif.json
          # Write inspections report in specified format [Xml, Html, Text, Sarif]
          format: # optional, default is Sarif
          # Run up to N jobs in parallel. 0 means as many as possible
          jobs: # optional, default is 0
          # Use absolute paths in inspections report
          absolute-paths: # optional, default is False
          # Force disable solution-wide analysis
          no-swea: # optional, default is False
          # Force enable solution-wide analysis
          swea: # optional, default is False
          # Analyze only projects selected by provided wildcards (default: analyze all projects in solution)
          project: # optional
          # Analyze only files selected by provided wildcards (default: analyze all files in solution)
          include: # optional
          # Exclude files selected by provided wildcards from analysis (default: analyze all files in solution)
          exclude: # optional
          # Dump issues types
          dumpIssuesTypes: # optional, default is False
          # Minimal severity level to report [INFO, HINT, SUGGESTION, WARNING, ERROR]
          sEverity: # optional, default is SUGGESTION
          # Show debugging messages
          debug: # optional, default is False
          # Display this amount of information [OFF, FATAL, ERROR, WARN, INFO, VERBOSE, TRACE]
          verbosity: # optional, default is INFO
          # Show help and exit
          help: # optional
          # Show tool version and exit
          version: # optional
          # MsBuild toolset version. Highest available is used by default. Example: --toolset=12.0
          toolset: # optional
          # MsBuild toolset (exe/dll) path. Example: --toolset-path=/usr/local/msbuild/bin/current/MSBuild.exe
          toolset-path: # optional
          # Mono path. Empty to ignore Mono. Not specified for autodetect. Example: --mono=/Library/Frameworks/Mono.framework/Versions/Current/bin/mono
          mono: # optional
          # .NET Core path. Empty to ignore .NET Core. Not specified for autodetect. Example: --dotnetcore=/usr/local/share/dotnet/dotnet
          dotnetcore: # optional
          # .NET Core SDK version. Example: --dotnetcoresdk=8.0.100
          dotnetcoresdk: # optional
          # Disable specified settings layers. Possible values: GlobalAll, GlobalPerProduct, SolutionShared, SolutionPersonal, ProjectShared, ProjectPersonal
          disable-settings-layers: # optional
          # Suppress global, solution and project settings profile usage. Alias for --disable-settings-layers:GlobalAll;GlobalPerProduct;SolutionShared;SolutionPersonal;ProjectShared;ProjectPersonal
          no-buildin-settings: # optional, default is False
          # Path to the directory where produced caches will be stored
          caches-home: # optional
          # MSBuild properties
          properties: # optional
          # MSBuild targets. These targets will be executed to get referenced assemblies of projects.
          targets-for-references: # optional
          # MSBuild targets. These targets will be executed to get other items (e.g. Compile item) of projects.
          targets-for-items: # optional
          # Install and use specified extensions
          eXtensions: # optional
          # Install extensions from specified source(s)
          source: # optional
          # Measure own tool's performance [MEMORY, SAMPLING, TIMELINE]
          measure: # optional
          # Do not build solution before processing
          no-build: # optional, default is False
          # Build solution before processing
          build: # optional, default is True
          # MsBuild target to execute before processing.
          target: # optional, default is Build
          # Solution file
          solution: # optional
          # Tool Version
          tool-version: # optional, default is 2025.2.3
           - name: Download a Build Artifact
  
  uses: actions/download-artifact@v7.0.0
  with:
    # Name of the artifact to download. If unspecified, all artifacts for the run are downloaded.
          name: all
    # IDs of the artifacts to download, comma-separated. Either inputs `artifact-ids` or `name` can be used, but not both.
           artifact-ids: # optional
    # Destination path. Supports basic tilde expansion. Defaults to $GITHUB_WORKSPACE
          path: c:\\users\obree\Github Downloads# optional
    # A glob pattern matching the artifacts that should be downloaded. Ignored if name is specified.
          pattern: # optional
    # When multiple artifacts are matched, this changes the behavior of the destination directories. If true, the downloaded artifacts will be in the same directory specified by path. If false, the downloaded artifacts will be extracted into individual named directories within the specified path.
          merge-multiple: # optional, default is false
    # The GitHub token used to authenticate with the GitHub API. This is required when downloading artifacts from a different repository or from a different workflow run. If this is not specified, the action will attempt to download artifacts from the current repository and the current workflow run.
          github-token: # optional
    # The repository owner and the repository name joined together by "/". If github-token is specified, this is the repository that artifacts will be downloaded from.
          repository: # optional, default is ${{ github.repository }}
    # The id of the workflow run where the desired download artifact was uploaded from. If github-token is specified, this is the run that artifacts will be downloaded from.
          run-id: # optional, default is ${{ github.run_id }}
          
